spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: demo-spring-boot
            items:
            - key: application.properties
              path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
